import { Concert, Subscriber, Sale, GalleryAlbum } from "./types";

export const concerts: Concert[] = [
  {
    id: "1",
    slug: "bad-bunny-cr-2026",
    artist: "Bad Bunny",
    title: "DEBÍ TIRAR MÁS FOTOS TOUR",
    date: "2026-12-15",
    time: "20:00",
    venue: "Estadio Nacional",
    city: "San José",
    description:
      "El conejo malo regresa a Costa Rica con su tour más ambicioso hasta la fecha. Una producción sin precedentes con miles de fanáticos. Prepárate para la noche de tu vida.",
    image: "/concerts/bad-bunny.jpg",
    coverImage: "/concerts/bad-bunny-cover.jpg",
    genre: ["Reggaeton", "Latin Trap", "Urbano"],
    featured: true,
    soldOut: false,
    tiers: [
      {
        id: "general",
        name: "General",
        price: 65000,
        available: 8500,
        total: 12000,
        perks: ["Acceso general al estadio"],
      },
      {
        id: "preferencial",
        name: "Preferencial",
        price: 120000,
        available: 2100,
        total: 3000,
        perks: ["Zona preferencial", "Acceso prioritario"],
      },
      {
        id: "vip",
        name: "VIP Golden",
        price: 250000,
        available: 380,
        total: 500,
        perks: ["Zona VIP", "Bar abierto", "Meet & Greet", "Merchandising exclusivo"],
      },
    ],
  },
  {
    id: "2",
    slug: "j-balvin-colores-2026",
    artist: "J Balvin",
    title: "COLORES TOUR",
    date: "2026-11-08",
    time: "21:00",
    venue: "Anfiteatro Juan Santamaría",
    city: "Alajuela",
    description:
      "El arcoíris del reggaeton llega con su show visual más espectacular. Luces, color y los mayores hits de su carrera en una sola noche.",
    image: "/concerts/j-balvin.jpg",
    coverImage: "/concerts/j-balvin-cover.jpg",
    genre: ["Reggaeton", "Urbano"],
    featured: true,
    soldOut: false,
    tiers: [
      {
        id: "general",
        name: "General",
        price: 55000,
        available: 4200,
        total: 6000,
      },
      {
        id: "vip",
        name: "VIP",
        price: 180000,
        available: 150,
        total: 300,
        perks: ["Zona VIP", "Barra libre", "Foto exclusiva"],
      },
    ],
  },
  {
    id: "3",
    slug: "ozuna-ozutochi-2026",
    artist: "Ozuna",
    title: "OZUTOCHI WORLD TOUR",
    date: "2026-10-25",
    time: "20:30",
    venue: "Estadio Ricardo Saprissa",
    city: "San José",
    description:
      "Ozuna el Negrito de Ojos Claros trae su tour mundial a Costa Rica. Más de 2 horas de sus mejores éxitos y una producción de clase mundial.",
    image: "/concerts/ozuna.jpg",
    coverImage: "/concerts/ozuna-cover.jpg",
    genre: ["Reggaeton", "Trap", "Urbano"],
    featured: false,
    soldOut: false,
    tiers: [
      {
        id: "general",
        name: "General",
        price: 50000,
        available: 5800,
        total: 8000,
      },
      {
        id: "preferencial",
        name: "Preferencial",
        price: 95000,
        available: 900,
        total: 1500,
      },
      {
        id: "vip",
        name: "VIP",
        price: 200000,
        available: 0,
        total: 200,
        perks: ["Zona VIP premium", "Meet & Greet", "Bar abierto"],
      },
    ],
  },
  {
    id: "4",
    slug: "feid-ferxxo-2026",
    artist: "Feid",
    title: "FERXXO NITRO JAMZ TOUR",
    date: "2026-09-06",
    time: "21:00",
    venue: "Centro de Eventos Pedregal",
    city: "San José",
    description:
      "El Ferxxo llega con toda la vibra. Sus temas más pegados, una producción brutal y una noche que no vas a querer perderte.",
    image: "/concerts/feid.jpg",
    coverImage: "/concerts/feid-cover.jpg",
    genre: ["Urbano", "Reggaeton", "R&B Latino"],
    featured: true,
    soldOut: false,
    tiers: [
      {
        id: "general",
        name: "General",
        price: 60000,
        available: 3500,
        total: 5000,
      },
      {
        id: "vip",
        name: "VIP Nitro",
        price: 220000,
        available: 80,
        total: 200,
        perks: ["Zona VIP", "Barra premium", "Merchandising", "Foto"],
      },
    ],
  },
  {
    id: "5",
    slug: "anuel-aa-2027",
    artist: "Anuel AA",
    title: "LA ÚLTIMA GIRA",
    date: "2027-01-20",
    time: "20:00",
    venue: "Estadio Nacional",
    city: "San José",
    description:
      "Real hasta la muerte. Anuel trae su última gira a Costa Rica con una producción histórica. El reggaeton más duro en la capital.",
    image: "/concerts/anuel.jpg",
    coverImage: "/concerts/anuel-cover.jpg",
    genre: ["Reggaeton", "Latin Trap"],
    featured: false,
    soldOut: true,
    tiers: [
      {
        id: "general",
        name: "General",
        price: 70000,
        available: 0,
        total: 10000,
      },
      {
        id: "vip",
        name: "VIP",
        price: 230000,
        available: 0,
        total: 400,
      },
    ],
  },
  {
    id: "6",
    slug: "karol-g-manana-2027",
    artist: "Karol G",
    title: "MAÑANA SERÁ BONITO TOUR",
    date: "2027-03-14",
    time: "20:00",
    venue: "Estadio Nacional",
    city: "San José",
    description:
      "La Bichota llega por primera vez a Costa Rica con su tour más grande. Ella misma, sus perreos y una producción que rompe con todo.",
    image: "/concerts/karol-g.jpg",
    coverImage: "/concerts/karol-g-cover.jpg",
    genre: ["Reggaeton", "Urbano", "Pop Latino"],
    featured: false,
    soldOut: false,
    tiers: [
      {
        id: "general",
        name: "General",
        price: 75000,
        available: 9000,
        total: 12000,
      },
      {
        id: "preferencial",
        name: "Preferencial",
        price: 140000,
        available: 2500,
        total: 3000,
      },
      {
        id: "vip",
        name: "VIP Bichota",
        price: 280000,
        available: 250,
        total: 500,
        perks: ["Zona VIP", "Meet & Greet", "Merchandising VIP", "Bar abierto"],
      },
    ],
  },
];

function makePhotos(count: number, accents: string[], aspects: ("square" | "wide" | "tall")[]): import("./types").GalleryPhoto[] {
  return Array.from({ length: count }, (_, i) => ({
    id: String(i + 1),
    alt: `Foto ${i + 1}`,
    accent: accents[i % accents.length],
    aspect: aspects[i % aspects.length],
  }));
}

export const galleryAlbums: GalleryAlbum[] = [
  {
    id: "1",
    slug: "bad-bunny-2024",
    artist: "Bad Bunny",
    eventTitle: "MOST WANTED TOUR",
    date: "2024-11-22",
    venue: "Estadio Nacional",
    city: "San José",
    coverAccent: "#1a0a2e",
    photos: makePhotos(14, ["#1a0a2e", "#2d1b4e", "#0d0520", "#3d0a6e"], ["wide", "square", "tall", "square", "square", "wide"]),
    videos: [
      { id: "v1", title: "Apertura del show — La noche perfecta", duration: "3:42", thumbnail: "" },
      { id: "v2", title: "TITÍ ME PREGUNTÓ — La gente reventó", duration: "5:11", thumbnail: "" },
      { id: "v3", title: "Resumen completo del concierto", duration: "12:30", thumbnail: "" },
    ],
  },
  {
    id: "2",
    slug: "myke-towers-2024",
    artist: "Myke Towers",
    eventTitle: "EASY MONEY BABY TOUR",
    date: "2024-09-14",
    venue: "Anfiteatro Juan Santamaría",
    city: "Alajuela",
    coverAccent: "#0a1f0a",
    photos: makePhotos(10, ["#0a1f0a", "#132b13", "#051505", "#1a3d1a"], ["square", "wide", "square", "tall", "square"]),
    videos: [
      { id: "v1", title: "LALA — El estadio cantó todo", duration: "4:15", thumbnail: "" },
      { id: "v2", title: "Highlights del show", duration: "8:00", thumbnail: "" },
    ],
  },
  {
    id: "3",
    slug: "jhay-cortez-2024",
    artist: "Jhay Cortez",
    eventTitle: "SIRENITA TOUR",
    date: "2024-07-06",
    venue: "Centro de Eventos Pedregal",
    city: "San José",
    coverAccent: "#0a1a2e",
    photos: makePhotos(12, ["#0a1a2e", "#102540", "#051020", "#1a3050"], ["tall", "square", "square", "wide", "square", "square"]),
    videos: [
      { id: "v1", title: "No Me Conoce — El momento del año", duration: "4:55", thumbnail: "" },
      { id: "v2", title: "Behind the scenes — Backstage completo", duration: "6:20", thumbnail: "" },
      { id: "v3", title: "Fan reactions — La gente lloró", duration: "2:45", thumbnail: "" },
    ],
  },
  {
    id: "4",
    slug: "sech-2025",
    artist: "Sech",
    eventTitle: "UN AÑO TOUR",
    date: "2025-02-15",
    venue: "Estadio Ricardo Saprissa",
    city: "San José",
    coverAccent: "#1f0a0a",
    photos: makePhotos(9, ["#1f0a0a", "#2e1010", "#100505", "#3d1515"], ["square", "square", "wide", "square", "tall"]),
    videos: [
      { id: "v1", title: "911 — El hit que paró todo", duration: "3:58", thumbnail: "" },
      { id: "v2", title: "Recap del show completo", duration: "10:15", thumbnail: "" },
    ],
  },
  {
    id: "5",
    slug: "maluma-2025",
    artist: "Maluma",
    eventTitle: "DON JUAN TOUR",
    date: "2025-05-10",
    venue: "Estadio Nacional",
    city: "San José",
    coverAccent: "#1a1000",
    photos: makePhotos(16, ["#1a1000", "#2a1a00", "#0f0a00", "#3d2a00"], ["wide", "square", "tall", "square", "square", "wide", "square", "tall"]),
    videos: [
      { id: "v1", title: "Hawái en vivo — Costa Rica se volvió loca", duration: "4:30", thumbnail: "" },
      { id: "v2", title: "Felices los 4 — Feat. sorpresa en el escenario", duration: "5:00", thumbnail: "" },
      { id: "v3", title: "Todo el show en 15 minutos", duration: "15:22", thumbnail: "" },
      { id: "v4", title: "Meet & Greet — Los afortunados del VIP", duration: "3:10", thumbnail: "" },
    ],
  },
];

export const subscribers: Subscriber[] = [
  { id: "1", email: "maria@gmail.com", name: "María Rodríguez", subscribedAt: "2026-01-15", plan: "vip" },
  { id: "2", email: "carlos@hotmail.com", name: "Carlos Jiménez", subscribedAt: "2026-02-03", plan: "free" },
  { id: "3", email: "ana@gmail.com", name: "Ana Mora", subscribedAt: "2026-02-20", plan: "vip" },
  { id: "4", email: "pedro@yahoo.com", name: "Pedro Ulate", subscribedAt: "2026-03-10", plan: "free" },
  { id: "5", email: "sofia@gmail.com", name: "Sofía Castro", subscribedAt: "2026-04-05", plan: "free" },
  { id: "6", email: "diego@gmail.com", name: "Diego Vargas", subscribedAt: "2026-04-18", plan: "vip" },
  { id: "7", email: "laura@hotmail.com", name: "Laura Brenes", subscribedAt: "2026-05-02", plan: "free" },
  { id: "8", email: "jose@gmail.com", name: "José Fonseca", subscribedAt: "2026-05-30", plan: "vip" },
];

export const sales: Sale[] = [
  {
    id: "1",
    orderNumber: "OF-2026-001",
    customer: "María Rodríguez",
    email: "maria@gmail.com",
    concertId: "4",
    concertTitle: "FERXXO NITRO JAMZ TOUR",
    items: [{ tierName: "General", quantity: 2, price: 60000 }],
    total: 120000,
    date: "2026-06-10",
    status: "confirmed",
  },
  {
    id: "2",
    orderNumber: "OF-2026-002",
    customer: "Carlos Jiménez",
    email: "carlos@hotmail.com",
    concertId: "1",
    concertTitle: "DEBÍ TIRAR MÁS FOTOS TOUR",
    items: [{ tierName: "VIP Golden", quantity: 1, price: 250000 }],
    total: 250000,
    date: "2026-06-11",
    status: "confirmed",
  },
  {
    id: "3",
    orderNumber: "OF-2026-003",
    customer: "Ana Mora",
    email: "ana@gmail.com",
    concertId: "2",
    concertTitle: "COLORES TOUR",
    items: [
      { tierName: "General", quantity: 3, price: 55000 },
      { tierName: "VIP", quantity: 1, price: 180000 },
    ],
    total: 345000,
    date: "2026-06-12",
    status: "pending",
  },
  {
    id: "4",
    orderNumber: "OF-2026-004",
    customer: "Pedro Ulate",
    email: "pedro@yahoo.com",
    concertId: "3",
    concertTitle: "OZUTOCHI WORLD TOUR",
    items: [{ tierName: "Preferencial", quantity: 2, price: 95000 }],
    total: 190000,
    date: "2026-06-13",
    status: "confirmed",
  },
  {
    id: "5",
    orderNumber: "OF-2026-005",
    customer: "Sofía Castro",
    email: "sofia@gmail.com",
    concertId: "5",
    concertTitle: "LA ÚLTIMA GIRA",
    items: [{ tierName: "General", quantity: 4, price: 70000 }],
    total: 280000,
    date: "2026-06-14",
    status: "refunded",
  },
];

export function formatPrice(price: number): string {
  return new Intl.NumberFormat("es-CR", {
    style: "currency",
    currency: "CRC",
    minimumFractionDigits: 0,
  }).format(price);
}

export function formatDate(dateStr: string): string {
  const date = new Date(dateStr + "T00:00:00");
  return date.toLocaleDateString("es-CR", {
    weekday: "long",
    year: "numeric",
    month: "long",
    day: "numeric",
  });
}
